"""Initial tables

Revision ID: 4b20dd215db0
Revises: 
Create Date: 2025-12-15 15:18:22.569597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b20dd215db0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_id'), 'rule', ['id'], unique=False)
    op.create_index(op.f('ix_rule_name'), 'rule', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('promptrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('intended_use', sa.String(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('reason_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promptrequest_id'), 'promptrequest', ['id'], unique=False)
    op.create_index(op.f('ix_promptrequest_user_id'), 'promptrequest', ['user_id'], unique=False)
    op.create_table('promptevaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('llm_status', sa.String(), nullable=True),
    sa.Column('llm_latency_ms', sa.Integer(), nullable=True),
    sa.Column('classification_json', sa.JSON(), nullable=True),
    sa.Column('triggered_rules_json', sa.JSON(), nullable=True),
    sa.Column('trace_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['promptrequest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_promptevaluation_id'), 'promptevaluation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promptevaluation_id'), table_name='promptevaluation')
    op.drop_table('promptevaluation')
    op.drop_index(op.f('ix_promptrequest_user_id'), table_name='promptrequest')
    op.drop_index(op.f('ix_promptrequest_id'), table_name='promptrequest')
    op.drop_table('promptrequest')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_rule_name'), table_name='rule')
    op.drop_index(op.f('ix_rule_id'), table_name='rule')
    op.drop_table('rule')
    # ### end Alembic commands ###
